/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"

*/



class Solution {
public:
    char findTheDifference(string s, string t) {
        
        char result = '\0';
        unordered_map<char, int> umap;
        for(auto c:s){
            umap[c]++;
        }
        
        for(auto c:t) {
            
            if(umap.find(c) != umap.end()){
                umap[c]--;
                
            } else {
                result = c;
            }
        }

        for(auto c:umap){
            if(c.second < 0){
                result = c.first;
            }
        }
        return result;
    }
};
